#_Q.1 There is a 30% chance of a rain today, and a 40% chance your umbrella order will arrive on time. You are earge to walk in the rain today and cannot do so without either!...

# probability for A is 30%...
p_a = 30/100 

# probability for B is 40%...
p_b = 40/100

# prints joint probability...
print('The joint probability is', p_a * p_b)

#_Q.2 There is a 30% chance of a rain today, and a 40% chance your umbrella order will arrive on time. You will be able to run errands only of it does not rain or yupr umbrella arrivs. What is the probabilitt it will not rain OR your umbrella arrives?...
    
# THIS QUESTION IS SAYS "NO RAIN", SO BE SUBSTRACTING THE PROBABILITY FROM 1.0...
    
# P(A OR B) = [1 - (P(A0)] + P(B) - [(P(A) × P(B)]

# probability for A is 30%...
p_a = 30/100 

# probability for B is 40%...
p_b = 40/100

# prints union probability...
print('The union probability is',(1 - p_a) + p_b - (p_a * p_b))

#_Q.3 There is a 30% chance of a rain today, and a 40% chance your umbrella order will arrive on time. What is the probability of it rains there is only a 20% chance your umbrella will arrive on time...

# probability for A is 30%...
p_a = 30/100 

# probability for B is 40%...
p_b = 40/100

# calculating conditional probability...
probability = p_a * p_b

# prints conditional probability...
print("Probability =", probability)

#_Q.4 You have 137 passengers booked on a flight from Las Vegas to Dallas. However, it is Lia Vegas on a Sunday morning and you estimate each passenger is 40% likely to not show up. You are trying to figure out how many seats to overbook so the plane does not fly empty. How likely is it at least 50 passengers will not show up?...

# importing binom from scipy.stats...
from scipy.stats import binom

# value for n, number of passengers...
n = 137

# value for p, estimate passengers probability...
p = 40/100

# value for p_50_or_more_noshows, 50 passengers will not show up...

p_50_or_more_noshows = 0.0

# applies for loop...
for x in range(50, 138):
    p_50_or_more_noshows += binom.pmf(x, n, p)
    
# prints p_50_or_more_noshows    
print(p_50_or_more_noshows)

#_Q.5 You flipped a coin 19 times and got head 15 times and tails 4 times. Do you think this coin has any good probability of being fair? Why or why not?...

# importing beta from scipy.stats...
from scipy.stats import beta

# value for heads...
heads = 8

# value for tails...
tails = 2

# formulate for p...
p = 1.0 - beta.cdf(0.5, heads, tails)

# prints p...
print(p)