#_Q.1 Is the value 62.6738 rational or irrational? Why or why not?

#_Q.2 Evaluate the expression: 10^7 × 10^-5. 
# formulates for evaluation...
Evaluation = 10 ** 7 * 10 ** -5

# prints evaluation... 
print(Evaluation)

#_Q.3 Evaluate the expression: 81^1/2.
# formulates for evaluation...
Evaluation = 81**(1/2)

# prints evaluation... 
print(Evaluation)

#_Q.4 Evaluate the expression: 25^3/2.
# formulates for evaluation...
Evaluation = 25**(3/2)

# prints evaluation... 
print(Evaluation)

#_Q.5 Assuming no payments are made, how much would a $1,000 lone be a worth at 5% interest compounded monthly after 3 years? 
# importing exp from math... 
from math import exp

# principal...
p = 1000

# rate of interest...
r = 0.05

# time period...
t = 3

# number of months...
n = 12

# calculating monthly compound interest as a... 
a = p * (1 + (r / n)) ** (n * t)

# prints compound interest as a... 
print(a)

#_Q.6 Assuming no payments are made, how much would a $1,000 lone be a worth at 5% interest compounded continuously after 3 years? 
# importing exp from math... 
from math import exp

# principal...
p = 1000

# rate of interest...
r = 0.05

# time, number of years... 
t = 3.0

# Calculating continuously compound as a... 
a = p * exp(r * t)

# prints continuously compound as a... 
print(a)

#_Q.7 For function f(x) = 3x²+1 what is a slope at x = 3?
# importing * from sympy... 
from sympy import *

# declear x to sympy... 
x = symbols('x')

# declear function... 
f = 3 * x ** 2 + 1

# calculate derivative of the function...
dx_f = diff(f)

# prints dx_f...
print(dx_f)

# prints dx_f for x, 3...
print(dx_f.subs(x, 3))

#_Q.8 For function f(x) = 3x²+1 what is the area under the cuver of x between 0 and 2?
# importing * from sympy... 
from sympy import *

# declear x to sympy... 
x = symbols('x')

# declear function... 
f = 3 * x ** 2 + 1

# calculate the integeral of the function with respect to x...
# for the area between x = 0 and 2...
area = integrate(f, (x, 0, 2))

# prints area...
print(area)